### ISSUE TITLE
Supposed to work for arbitrary square matrix inputs?

### ISSUE THREAD

**Issue by crstnbr** [noponen/CyclicDiagonal.jl#3]
I see that all your tests pass. However, the matrices in your tests seem to be rather "constructed".

Is the factorization supposed to work for arbitrary square input matrices `M`?

Example:
```julia
julia> M = [1 2 3; 4 5 6; 7 8 9]
3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

julia> D1,C,D2 = CyclicDiagonal.iterDCD(M);

julia> M ≈ D1*C*D2 # why?
false

julia> D1*C*D2 - M
3×3 Array{Float64,2}:
  0.203501     0.00496046  -0.286479
  0.00908604  -0.736701     0.762608
 -0.723338     0.921685     0.0335098

julia> D1,C,D2 = CyclicDiagonal.iterDCD(M, 1e8, 1e-8); # more iterations, lower tolerance

julia> D1*C*D2 - M # identical result?
3×3 Array{Float64,2}:
  0.203501     0.00496018  -0.28648
  0.00908627  -0.736701     0.762608
 -0.723337     0.921686     0.0335105
```

**Comment by noponen** [comment]
Hi,

I can respond better tomorrow, but shortly this decomposition represents a
general nxn matrix A with n^2 free parameters using only 3n free parameters
(the two diagonals and the circulant vector).

The accuracy should be compared to that of e.g. best rank 1 approximation
u*v' of A with the vectors u and v corresponding to the highest singular
value of A... The rank 1 approximation has 2n free parameters (u and v).

So, we cannot achieve perfect decomposition for a general matrix but an
approximate one.

I haven't tested the matrices you sent but supposedly the method already
found closest approximation with fewer iterations / lower tolerance and
could not improve it due to the above mentioned limitations.

**Comment by noponen** [comment]
Indeed for the given M, it happens so that the rank 1 approximation via svd has similar magnitude

```julia
julia> F = svd(M)

julia> F.U[:,1]*F.S[1]*F.Vt[1,:]'  # rank 1 reconstruction
3×3 Array{Float64,2}:
 1.73622  2.07174  2.40727
 4.20715  5.02019  5.83322
 6.67809  7.96863  9.25917

julia> R_svd = F.U[:,1]*F.S[1]*F.Vt[1,:]' - M # rank 1 residual
3×3 Array{Float64,2}:
  0.736218   0.0717425  -0.592733
  0.207153   0.0201865  -0.16678 
 -0.321912  -0.0313695   0.259173

julia> R_dcd = D1*C*D2 - M # dcd residual
3×3 Array{Float64,2}:
  0.203501     0.00496046  -0.286479
  0.00908604  -0.736701     0.762608
 -0.723338     0.921685     0.0335098

julia> norm( R_svd ) # Frobenius norm
1.0683695145547085

julia> norm( R_dcd ) # Frobenius norm
1.619176916047037
```

**Comment by crstnbr** [comment]
Thanks for the explanation. The rank 1 approximation should perhaps be mentioned in the README then?

**Comment by noponen** [comment]
Added a little bit on this in the README
